setwd("/Users/laavanyaganesh/Desktop/SAS&R/")
train<-read.csv("ANAL00.csv")
str(train)
colnames(train)
train<-subset(train,select = -c(rand,RespHoldout))
colnames(train)
install.packages("randomForest")
library(randomForest)
rf<-randomForest(x=train[-c(1,8)],y=train$Resp,ntree=200,importance = TRUE)
test<-read.csv("HOLD00.csv")
ls()
str(test)
colnames(test)
test<-subset(test,select = -c(Resp))
colnames(test)
test$Resp<-test$RespHoldout
test<-subset(test,select = -c(rand,RespHoldout))
test$rf<-predict(rf,test)
str(test)
install.packages("earth")
library(earth)
mars<-earth(x=train[-c(1,8)],y=train$Resp)
ls()
summary(mars,digits=2,style="pmax")
test$marspred<-predict(mars,test)
str(test)
install.packages("rpart")
Library(rpart)
tree<-rpart(Resp~.,data=train[-c(1)],control=rpart.control(cp=.003))
plot(tree,uniform = TRUE,main="Classification Tree for S6 Data")
text(tree,use.n = TRUE,all = TRUE,cex=.8)
test$treepred<-predict(tree,test)
str(test)
write.csv(test,file = "test.csv")
